import { Navbar } from "@/components/Navbar";
import "./reset.css";
import "./global.css";

export const metadata = {
  title: "Acquire Platform",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="page-content">{children}</div>
      </body>
    </html>
  );
}
